### ISSUE TITLE
Add translations for other languages

### ISSUE THREAD

**Issue by timokoenig** [timokoenig/covid-validator#1]
We welcome anyone to help us translate this app in as many languages as possible.

https://github.com/timokoenig/covid-validator#i18n

**Comment by Ein-Tim** [comment]
🙋🏻‍♂️ I'd be more than happy to provide German and French translation. 

Let me know what to do!

**Comment by timokoenig** [comment]
@Ein-Tim sounds good! Will let you know when I have the JSON prepared

**Comment by Ein-Tim** [comment]
Nice, I'll take a look as soon as I can.

**Comment by Ein-Tim** [comment]
PR for German translation arrives soon.

**Comment by timokoenig** [comment]
@Ein-Tim that's awesome. Thank you so much!

**Comment by Ein-Tim** [comment]
@timokoenig For sure: #16

**Comment by timokoenig** [comment]
Now we have English and German. French and Spanish are in the pipeline. I will close this issue because this will be an ongoing task and we have the instructions in the [README](https://github.com/timokoenig/covid-validator#i18n)

**Comment by Ein-Tim** [comment]
Working on French translation now, sorry for the delay. 🚧

**Comment by timokoenig** [comment]
@Ein-Tim no worries, this is not very urgent
