### ISSUE TITLE
Make this a PWA (standalone display mode)

### ISSUE THREAD

**Issue by Ein-Tim** [timokoenig/covid-validator#13]
It would be great to have this app as a PWA, like [schnelltesttest.de](https://github.com/zerforschung/schnelltesttest.de).
This means that if the user adds this page to the Home Screen, an "Web App" is created. Thus, the user doesn't see the Safari elements anymore at all but only the app. 

I hope you understand what I mean 😅

**Comment by timokoenig** [comment]
It should already be a PWA but it is missing several assets. I'm currently working on those and will update the site tomorrow

**Comment by Ein-Tim** [comment]
Currently it opens Safari for me (like a bookmark). Thanks for working on it!

**Comment by timokoenig** [comment]
@Ein-Tim just changed a few things. Can you check again, please?

**Comment by Ein-Tim** [comment]
Great, this works now! Thank you! 

Closing as implemented.
