### ISSUE TITLE
Select language before onboarding / based on default language

### ISSUE THREAD

**Issue by Ein-Tim** [timokoenig/covid-validator#17]
If a user accesses the site for the first time, the onboarding is shown. However, there is no option to change the language prior to this at the moment. 

This should be possible.

**Comment by timokoenig** [comment]
I wanted to implement the feature that the default language is based on the users browser language. In case the user wants to have the validator in a different language I added the "Preferred Language" in the settings. Do you agree with it?

**Comment by Ein-Tim** [comment]
@timokoenig Yes, this sounds like a good idea!

**Comment by timokoenig** [comment]
Added the language detection
