### ISSUE TITLE
Automatically close Result view after x seconds

### ISSUE THREAD

**Issue by timokoenig** [timokoenig/covid-validator#22]
On a few occasions I noticed that the verifier left the result view open after successfully scanning a certificate. This is a potential privacy issue if the device would be left unattended because of the Name and Birthdate that is being displayed there.

The idea is to automatically close the result view after x (maybe 20 or 30) seconds to remove the personal information from the previous scan.

**Comment by sqonde** [comment]
I will do that.

Maybe it will be good to have the possibility to extend the Autoclose?! 
Lets see what the users says... ☕️
