### ISSUE TITLE
German flag is very small

### ISSUE THREAD

**Issue by Ein-Tim** [timokoenig/covid-validator#25]
The German flag is very small compared to the flag from other countries.

Germany:

<img src="https://user-images.githubusercontent.com/67682506/153685684-dbd1d9d6-4d8f-4f81-8006-be38b7e43d6b.jpeg" width="300">

Austria:

<img src="https://user-images.githubusercontent.com/67682506/153685759-353f077e-3e5e-4279-a76e-a4dad8b843f2.jpeg" width="300">

**Comment by timokoenig** [comment]
Thanks! Should already be fixed with the newest version that I will deploy tomorrow. I will test it again

**Comment by timokoenig** [comment]
Just deployed the new version
