### ISSUE TITLE
Custom Rule Builder

### ISSUE THREAD

**Issue by timokoenig** [timokoenig/covid-validator#4]
Rules change so much nowadays that it is almost impossible to keep up with the regulations. Every state and sometimes even every city or company have their own rules. We can offer a rule builder where companies can create their own rule set that meet their need.

- [x] Create overview of current regulations
- [x] Implement rule build that allows to create custom rules
- [x] Save custom rules in local storage

**Comment by timokoenig** [comment]
I started a collection of current EU and local rules [here](https://github.com/timokoenig/covid-validator/tree/main/docs)

**Comment by timokoenig** [comment]
First version of the custom rule builder is done. I'm going to create local rules for Hamburg and then write a few tests to see how it works. If everything works as expected I will deploy the rule builder tonight or tomorrow

**Comment by Ein-Tim** [comment]
@timokoenig I guess https://github.com/timokoenig/covid-validator/tree/rule-builder is the branch you are working on, right? Then I could test this feature locally.

**Comment by timokoenig** [comment]
@Ein-Tim that's correct but you won't be able to select those rules at the moment therefore a testing is kinda difficult. Will let you know when this is implemented

**Comment by Ein-Tim** [comment]
Okay thanks, I can also translate this into German/French again. 

I'm trying to get French translation ready by the end of this week, but I'm so busy at the moment.

**Comment by timokoenig** [comment]
IMO translations for the rule builder is not necessary until its fully functional and tested

**Comment by Ein-Tim** [comment]
Yeah for sure, I meant after it is finished!

**Comment by timokoenig** [comment]
Update: I started creating several test cases and noticed and few problems. The "official" certlogic library doesn't support certain (very basic) operations. I created locally a clone that does everything we need but I will try to bring those changes in the official library. Until then I most likely publish my own certlogic package with these adjustments to continue with this feature

**Comment by timokoenig** [comment]
Just tested successfully the local rules from Hamburg.

```
 PASS  tests/custom-rules.test.ts
  ✓ BioNTech; Partial Immunization; INVALID (2 ms)
  ✓ BioNTech; Full Immunization; VALID (1 ms)
  ✓ BioNTech; Full Immunization shortly after vaccination; INVALID (2 ms)
  ✓ BioNTech; Full Immunization in one year; INVALID (1 ms)
  ✓ BioNTech; Full Immunization after Recovery; VALID
  ✓ BioNTech; Full Immunization after Recovery shortly after vaccination; VALID (1 ms)
  ✓ BioNTech; Booster Immunization; VALID (1 ms)
  ✓ BioNTech; Booster Immunization shortly after vaccination; VALID (1 ms)
  ✓ BioNTech; Booster Immunization in one year; VALID
  ✓ BioNTech; Booster Immunization after Recovery; VALID
  ✓ J&J; Partial Immunization; INVALID (1 ms)
  ✓ J&J; Full Immunization; VALID (1 ms)
  ✓ J&J; Booster Immunization; VALID (1 ms)
  ✓ J&J; Booster Immunization after Recovery; VALID (1 ms)
  ✓ Special; Full Immunization with unregistered mp; INVALID (1 ms)
  ✓ Recovery after 10 days; INVALID
  ✓ Recovery after 30 days; VALID (1 ms)
  ✓ Antigen after 10 hours; VALID
  ✓ Antigen after 30 hours; INVALID (1 ms)
  ✓ PCR after 10 hours; VALID
  ✓ PCR after 80 hours; INVALID (1 ms)
  ✓ Unknown Test after 10 hours; INVALID (1 ms)
```

Next up:
- [ ] Clean up the feature branch
- [ ] Check the state rules for Germany
- [ ] Create all state rules
- [ ] Add documentation for rule builder and state rules
- [ ] Deploy rule builder and state rules

**Comment by timokoenig** [comment]
Just deployed the new version with the first version of the rule builder. Many more enhancements will be made but that will be tracked in separate tickets like https://github.com/timokoenig/covid-validator/issues/28
